dataset: "siva"
# mask_name: 'ukb2907-smri-aal2'
subspace: "iva" # [2,4]
eta: [1]
beta: [0.5]
lam: [1.102657790843584]
input_dim: [30, 30, 30]
output_dim: [30, 30, 30]

special:
  nRuns: 1
  epochs: 500
  batch_size: 2907
  lr: 0.00000001